# Generated by Django 4.2 on 2023-05-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_pizza_pizzacategory_remove_menupizzas_toppings_and_more'),
        ('offer', '0002_alter_offer_email_alter_offer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='favorite_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pizza.pizza'),
        ),
    ]
