# Generated by Django 4.2 on 2023-05-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_offer_favorite_pizza'),
        ('pizza', '0003_pizza_pizzacategory_remove_menupizzas_toppings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuPizzas',
        ),
    ]
