# Generated by Django 4.2 on 2023-05-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_orderitemoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemoffer',
            old_name='order',
            new_name='order2',
        ),
    ]