# Generated by Django 4.2 on 2023-05-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_order_orderitemoffer_order2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemoffer',
            old_name='order2',
            new_name='order',
        ),
    ]