# Generated by Django 4.2 on 2023-05-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_contactinformation_order'),
        ('cart', '0007_rename_order2_orderitemoffer_order'),
    ]

    operations = [
    ]
