# Generated by Django 4.2 on 2023-05-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_merge_20230509_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.CharField(default='no-contact@ru.is', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='name',
            field=models.CharField(default='John Doe', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='phone_number',
            field=models.CharField(default='112', max_length=200),
        ),
    ]
