# Generated by Django 4.2 on 2023-05-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_merge_20230510_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
