# Generated by Django 4.2 on 2023-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_contactinformation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('CVC', models.IntegerField()),
            ],
        ),
    ]
