# Generated by Django 4.2 on 2023-05-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='CVC',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.CharField(max_length=200),
        ),
    ]
