# Generated by Django 4.2 on 2023-05-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_payment_cvc_alter_payment_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='country',
            field=models.CharField(default='Iceland'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cardholder_name',
            field=models.CharField(default='jonni', max_length=200),
            preserve_default=False,
        ),
    ]
