# Generated by Django 4.2 on 2023-05-10 16:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_contactinformation_country_payment_cardholder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
