# Generated by Django 4.2 on 2023-05-10 16:24

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_contactinformation_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='CVC',
            field=creditcards.models.SecurityCodeField(max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=creditcards.models.CardNumberField(max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardholder_name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=creditcards.models.CardExpiryField(),
        ),
    ]
