# Generated by Django 4.2 on 2023-05-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_merge_20230510_1157'),
        ('cart', '0016_alter_payment_cvc_alter_payment_card_number_and_more'),
    ]

    operations = [
    ]
